version: 2
jobs:
  build:
    working_directory: ~/cci-demo-phoenix
    docker:
      - image: trenpixster/elixir:1.4.2
    steps:
      - checkout
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
